### ISSUE TITLE
The const JavaScript keyword has the same color as the constant itself.

### ISSUE THREAD

**Issue by RamirezAlex** [sdras/night-owl-vscode-theme#166]
The `const` keyword has the same color as the constant itself in JavaScript.

Expected to use different color for better contrast.

![image](https://user-images.githubusercontent.com/1482473/51436266-f898b280-1c57-11e9-9a3b-2908997111ab.png)

![image](https://user-images.githubusercontent.com/1482473/51437281-238c0200-1c6a-11e9-895b-1f18908275b5.png)

![image](https://user-images.githubusercontent.com/1482473/51437295-5930eb00-1c6a-11e9-8d15-bb6c9dc78afa.png)

**Comment by sdras** [comment]
UGH YES this one is driving freaking batty. I'm going to close your PR because I want to make the const purple and ital as a keyword and remove the ital from the variable. But open to another PR, otherwise I'll do it myself when this project is done. This will have to get fixed because it's driving me crazy.

**Comment by RamirezAlex** [comment]
@sdras that sounds good, I can create a new PR. Any specific purple that you want?

**Comment by sdras** [comment]
This is fixed! Yay!

**Comment by xg-wang** [comment]
Hi @sdras thanks for working on this issue. Seems the new version fixed the function keyword but const is still having the same color.

**Comment by xg-wang** [comment]
Ah it's when it's inside a class member function
![image](https://user-images.githubusercontent.com/8369011/55746780-7f576300-59ef-11e9-8378-9cb2e8c2a5dc.png)
